font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        12.0

# Transparencia y fondo
background_opacity 0.90
background #1a1b26
foreground #c0caf5

# Cursor
cursor #c0caf5
cursor_text_color #1a1b26
cursor_shape beam
cursor_beam_thickness 1.5

# Selección
selection_background #283457
selection_foreground #c0caf5

# Colores Tokyo Night
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# Ventana
window_padding_width 12
remember_window_size  yes
initial_window_width  1000
initial_window_height 650

# Tabs
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_background #1a1b26
active_tab_background #7aa2f7
active_tab_foreground #1a1b26
inactive_tab_background #1a1b26
inactive_tab_foreground #a9b1d6

# General
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0.0
scrollback_lines 10000
copy_on_select yes
strip_trailing_spaces smart

# URL
url_color #7aa2f7
url_style curly
open_url_with default
